http:
  routers:
    web:
      entryPoints:
        - "web"
      rule: "Host(`web.example.com`)"
      service: nginx

  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://web:80
