version: "3.7"

volumes:
  nextcloud:
  db:

networks:
  default:
    external:
      name: traefik-network

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.2.0
    read_only: true
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/traefik.yaml:ro
      - ./traefik/etc/traefik:/etc/traefik/
      - ./traefik/srv/letsencrypt:/letsencrypt

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    hostname: "${TRANSMISSION_HOST}.${DOMAIN_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRANSMISSION_HOST}.rule=Host(`${TRANSMISSION_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${TRANSMISSION_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${TRANSMISSION_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${TRANSMISSION_HOST}.loadbalancer.server.port=9091"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_LOGIN}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - /home/ksmi/transmission/config/:/config
      - /home/ksmi/a/plex/movies/:/downloads
      - /home/ksmi/plex/movies/:/downloadsSSD
      - /home/ksmi/a/plex/tv/:/serialsHHD
      - /home/ksmi/a/plex/music/:/music
      - /home/ksmi/a/transmission/watch/:/watch
    ports:
      - 9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: "${PLEX_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM="claim-mBWf_FXSdKwkYfzzPFZf"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PLEX_HOST}.rule=Host(`${PLEX_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PLEX_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${PLEX_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${PLEX_HOST}.loadbalancer.server.port=32400"
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - ./plex/config:/config
      - /home/ksmi/a/plex/tv:/tv
      - /home/ksmi/a/plex/movies:/movies
      - /home/ksmi/a/plex/movies:/moviesHHD
      - /home/ksmi/a/plex/tv:/serialsHHD
      - /home/ksmi/a/plex/music/:/music
    restart: unless-stopped

  youtrack:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack"
    hostname: "${YOUTRACK_HOST}.${DOMAIN_NAME}"
    volumes:
      - ./youtrack/srv/youtrack/data/:/opt/youtrack/data
      - ./youtrack/srv/youtrack/conf/:/opt/youtrack/conf
      - ./youtrack/srv/youtrack/logs/:/opt/youtrack/logs
      - ./youtrack/srv/youtrack/backups/:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${YOUTRACK_HOST}.rule=Host(`${YOUTRACK_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${YOUTRACK_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${YOUTRACK_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${YOUTRACK_HOST}.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.${NEXT_CLOUD_HOST}.headers.STSPreload=true"
      - "traefik.http.middlewares.${NEXT_CLOUD_HOST}.headers.STSSeconds=315360000"
    restart: unless-stopped

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    hostname: "${NEXT_CLOUD_HOST}.${DOMAIN_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.rule=Host(`${NEXT_CLOUD_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${NEXT_CLOUD_HOST}.loadbalancer.server.port=80"
    ports:
      - 80
    links:
      - nextcloud_db
    volumes:
      - ./nextcloud/app:/var/www/html
      - /home/ksmi/a/nextcloud/data:/var/www/html/data
    restart: always

  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXT_CLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXT_CLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXT_CLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXT_CLOUD_MYSQL_USER}

  cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
      - nextcloud_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud_db

  bind:
    restart: always
    image: sameersbn/bind:9.16.1-20200524
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - ./bind:/data
    environment:
      - WEBMIN_INIT_SSL_ENABLED=false

