version: "3.7"

networks:
  default:
    external:
      name: traefik-network

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=krrllsm@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "443:443"
      - "80:80"
      - "8070:8080"
    volumes:
      - "./traefik/srv/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    network: traefik-network

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.transmission.loadbalancer.server.port=8080"
      - "traefik.http.routers.transmission.rule=Host(`transmission.example.com`)"
#      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
      - traefik.port=80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=ksmi
      - PASS=112233
    volumes:
      - /home/ksmi/transmission/config/:/config
      - /home/ksmi/a/plex/movies/:/downloads
      - /home/ksmi/plex/movies/:/downloadsSSD
      - /home/ksmi/a/plex/tv/:/serialsHHD
      - /home/ksmi/a/transmission/watch/:/watch
    ports:
      - 8383:80
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    network: traefik-network

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-ti3CyARHrBcrK-Ei5oav
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.plex.rule=Host(`promfis.ru`)"
      - "traefik.frontend.rule=Host:promfis.ru"
      - "traefik.port=32400"
    volumes:
      - ./plex/config:/config
      - /home/ksmi/a/plex/tv:/tv
      - /home/ksmi/a/plex/movies:/movies
      - /home/ksmi/a/plex/movies:/moviesHHD
      - /home/ksmi/a/plex/tv:/serialsHHD
    restart: unless-stopped
    network: traefik-network

