version: "3.7"
networks:
  default:
    external:
      name: traefik-network

services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/custom/:/custom/:ro

  web:
    image: nginx:latest
    container_name: web
    hostname: web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    hostname: transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=ksmi
      - PASS=112233
    volumes:
      - ./transmission/config/:/config
      - /home/ksmi/a/plex/movies/:/downloads
      - /home/ksmi/a/plex/tv/:/serialsHHD
      - /home/ksmi/a/transmission/watch/:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
