version: "3.7"

volumes:
  nextcloud:
  db:

networks:
  default:
    external:
      name: traefik-network

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.2.0
    read_only: true
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/traefik.yaml:ro
      - ./traefik/etc/traefik:/etc/traefik/
      - ./traefik/srv/letsencrypt:/letsencrypt

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TORRENT_HOST}.rule=Host(`${TORRENT_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${TORRENT_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${TORRENT_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${TORRENT_HOST}.loadbalancer.server.port=9092"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=9092
    volumes:
      - ./qbittorrent/config/:/config
      - /home/ksmi/a/plex/movies/:/downloads
      - /home/ksmi/a/plex/tv/:/s
      - /home/ksmi/a/plex/music/:/m
    ports:
      - 9092:9092
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

#  transmission:
#    image: linuxserver/transmission
#    container_name: transmission
#    hostname: "${TRANSMISSION_HOST}.${DOMAIN_NAME}"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.${TRANSMISSION_HOST}.rule=Host(`${TRANSMISSION_HOST}.${DOMAIN_NAME}`)"
#      - "traefik.http.routers.${TRANSMISSION_HOST}.entrypoints=websecure"
#      - "traefik.http.routers.${TRANSMISSION_HOST}.tls.certresolver=mydnschallenge"
#      - "traefik.http.services.${TRANSMISSION_HOST}.loadbalancer.server.port=9091"
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
#      - USER=${TRANSMISSION_LOGIN}
#      - PASS=${TRANSMISSION_PASS}
#    volumes:
#      - ./transmission/config/:/config
#      - /home/ksmi/a/plex/movies/:/downloads
#      - /home/ksmi/plex/movies/:/downloadsSSD
#      - /home/ksmi/a/plex/tv/:/s
#      - /home/ksmi/a/plex/music/:/m
#      - /home/ksmi/a/transmission/watch/:/w
#    ports:
#      - 9091
#      - 51413:51413
#      - 51413:51413/udp
#    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: "${PLEX_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM="claim-mBWf_FXSdKwkYfzzPFZf"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PLEX_HOST}.rule=Host(`${PLEX_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PLEX_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${PLEX_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${PLEX_HOST}.loadbalancer.server.port=32400"
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - ./plex/config:/config
      - /home/ksmi/a/plex/tv:/tv
      - /home/ksmi/a/plex/movies:/movies
      - /home/ksmi/a/plex/movies:/moviesHHD
      - /home/ksmi/a/plex/tv:/serialsHHD
      - /home/ksmi/a/plex/music/:/music
      - /home/ksmi/a/plex/likedMusic/:/likedMusic
    restart: unless-stopped

  youtrack:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack"
    hostname: "${YOUTRACK_HOST}.${PROMFIS_DOMAIN}"
    volumes:
      - ./youtrack/srv/youtrack/data/:/opt/youtrack/data
      - ./youtrack/srv/youtrack/conf/:/opt/youtrack/conf
      - ./youtrack/srv/youtrack/logs/:/opt/youtrack/logs
      - ./youtrack/srv/youtrack/backups/:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${YOUTRACK_HOST}.rule=Host(`${YOUTRACK_HOST}.${PROMFIS_DOMAIN}`)"
      - "traefik.http.routers.${YOUTRACK_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${YOUTRACK_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${YOUTRACK_HOST}.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.${YOUTRACK_HOST}.headers.STSPreload=true"
      - "traefik.http.middlewares.${YOUTRACK_HOST}.headers.STSSeconds=315360000"
    restart: unless-stopped

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    hostname: "${NEXT_CLOUD_HOST}.${DOMAIN_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.rule=Host(`${NEXT_CLOUD_HOST}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.entrypoints=websecure"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.tls.certresolver=mydnschallenge"
      - "traefik.http.services.${NEXT_CLOUD_HOST}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cloud.headers.STSPreload=true"
      - "traefik.http.middlewares.cloud.headers.STSSeconds=15552000"
      - "traefik.http.middlewares.cloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.cloud-dav.replacepathregex.replacement=/remote.php/dav/"
      - "traefik.http.routers.${NEXT_CLOUD_HOST}.middlewares=cloud,cloud-dav"
    ports:
      - 80
    links:
      - nextcloud_db
      - nextcloud_redis
    volumes:
      - ./nextcloud/app:/var/www/html
      - /home/ksmi/a/nextcloud/data:/var/www/html/data
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_PASSWORD=${NEXT_CLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXT_CLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXT_CLOUD_MYSQL_USER}
      - MYSQL_HOST=nextcloud_db
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    entrypoint: sh -c "apt update && apt install -y libmagickcore-6.q16-6-extra && /entrypoint.sh apache2-foreground"

  nextcloud_redis:
    image: redis
    container_name: nextcloud_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXT_CLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXT_CLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXT_CLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXT_CLOUD_MYSQL_USER}

  cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud_cron
    restart: always
    network_mode: none
    depends_on:
      - nextcloud_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud_app
      - NEXTCLOUD_EXEC_SHELL=sh
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=5

  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: home_pure_ftpd
    hostname: ftpserver
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - /home/ksmi/a:/home/ksmi
      - /etc/pure-ftpd/passwd:/etc/pure-ftpd/passwd
    command: /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P 0.0.0.0 -s -A -j -Z -H -4 -E -R -X -x
    environment:
      - PUBLICHOST=0.0.0.0
      - FTP_USER_NAME=ksmi
      - FTP_USER_PASS=112233
      - FTP_USER_HOME=/home/ksmi
    restart: always

  ksmi_site:
    image: ksmi/site:latest
    container_name: ksmi_site
    hostname: "${DOMAIN_NAME}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ksmi.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.ksmi.entrypoints=websecure
      - traefik.http.routers.ksmi.tls.certresolver=mydnschallenge
      - traefik.http.services.ksmi.loadbalancer.server.port=80

    restart: always
