version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    volumes:
      - ${DATA_DIR}/adguard/work:/opt/adguardhome/work
      - ${DATA_DIR}/adguard/conf:/opt/adguardhome/conf
    ports:
      - "80"
      - "63:53/tcp"
      - "63:53/udp"
    restart: unless-stopped
