version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - CLI_ARGS="--run-script-before = /telegram/telegram.sh, --run-script-after = /telegram/telegram.sh"
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
    volumes:
      - ${DATA_DIR}/duplicati/config:/config
      - ${DATA_DIR}/duplicati/backups:/backups
      - ${DATA_DIR}/duplicati/telegram:/telegram
      - ${CONTENT_DIR}/nextcloud:/source/nextcloud
    restart: unless-stopped
