version: "3.7"

networks:
  default:
    external:
      name: traefik-network

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: "${DUPLICATI_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - ../data/duplicati/config:/config
      - ../data//duplicati/backups:/backups
      - /home/ksmi/a/nextcloud:/source/nextcloud
    ports:
      - 8200:8200
    labels:
      - traefik.enable=true
      - traefik.http.routers.duplicati.rule=Host(`${DUPLICATI_HOST}.${DOMAIN_NAME}`)
      - traefik.http.routers.duplicati.entrypoints=websecure
      - traefik.http.routers.duplicati.tls.certresolver=mydnschallenge
      - traefik.http.services.duplicati.loadbalancer.server.port=8200
    restart: unless-stopped