version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    volumes:
      - ${DATA_DIR}/homer/assets:/www/assets
    restart: unless-stopped
