version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: "${JACKETT_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/jackett/config:/config
      - ../data/jackett/downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`${JACKETT_HOST}.${DOMAIN_NAME}`)
      - traefik.http.routers.jackett.entrypoints=websecure
      - traefik.http.routers.jackett.tls.certresolver=mydnschallenge
      - traefik.http.middlewares.jackettlist.ipwhitelist.sourcerange=192.168.0.0/24, 10.13.13.0/24, 127.0.0.1/32
      - traefik.http.routers.jackett.middlewares=jackettlist
      - traefik.http.services.jackett.loadbalancer.server.port=9117
    restart: unless-stopped
