version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: "${JACKETT_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/jackett/config:/config
      - ../data/jackett/downloads:/downloads
    restart: unless-stopped
