version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${DATA_DIR}/lidarr/config:/config
      - ${CONTENT_DIR}/torrent/music:/downloads
      - ${CONTENT_DIR}/plex/music:/music
    restart: unless-stopped
