version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/lidarr/config:/config
      - /home/ksmi/a/torrent/music:/downloads
      - /home/ksmi/a/plex/music:/music
    restart: unless-stopped
