version: "3.7"

networks:
  default:
    external:
      name: traefik-network

services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: "${NETDATA_HOST}.${DOMAIN_NAME}"
    ports:
      - 19999
    environment:
      - PUID=1000
      - PGID=1000
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.netdata.rule=Host(`${NETDATA_HOST}.${DOMAIN_NAME}`)
      - traefik.http.routers.netdata.entrypoints=websecure
      - traefik.http.routers.netdata.tls.certresolver=mydnschallenge
      - traefik.http.services.netdata.loadbalancer.server.port=19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ../data/netdata/netdataconfig/:/etc/netdata
      - ../data/netdata/netdatalib/:/var/lib/netdata
      - ../data/netdata/netdatacache/:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: unless-stopped
