version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    environment:
      - PUID=1000
      - PGID=1000
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${DATA_DIR}/netdata/netdataconfig/:/etc/netdata
      - ${DATA_DIR}/netdata/netdatalib/:/var/lib/netdata
      - ${DATA_DIR}/netdata/netdatacache/:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: unless-stopped
