version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    links:
      - nextcloud_db
      - nextcloud_redis
    volumes:
      - ../data/nextcloud/app:/var/www/html
      - /home/ksmi/a/nextcloud/data:/var/www/html/data
      - ../data/nextcloud/scripts/custom-entrypoint.sh:/custom-entrypoint.sh:ro
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_PASSWORD=${NEXT_CLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXT_CLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXT_CLOUD_MYSQL_USER}
      - MYSQL_HOST=nextcloud_db
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    entrypoint: sh -c "/custom-entrypoint.sh"

  nextcloud_redis:
    image: redis
    container_name: nextcloud_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ../data/nextcloud-db/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXT_CLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXT_CLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXT_CLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXT_CLOUD_MYSQL_USER}

  cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud_cron
    restart: always
    network_mode: none
    depends_on:
      - nextcloud_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ../data/nextcloud/cron/jobs.sh:/cron-scripts/jobs.sh:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud_app
      - NEXTCLOUD_EXEC_SHELL=sh
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
