version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    dns: ${PUBLICHOST}
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
    volumes:
      - ../data/overseerr/config:/app/config
    restart: unless-stopped
