version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - HTTP_PROXY=http://xray_proxy:10809
      - HTTPS_PROXY=http://xray_proxy:10809
      - NO_PROXY=localhost,127.0.0.1,plex,radarr,sonarr,lidarr,jackett,overseerr,tautulli,qbittorrent,xray_proxy,traefik,.ksmi.me,192.168.0.0/24,10.0.0.0/8,172.16.0.0/12
    volumes:
      - ../data/overseerr/config:/app/config
    restart: unless-stopped
