version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  owntracks:
    container_name: owntracks
    image: owntracks/recorder
    hostname: "${OWNTRACKS_HOST}.${DOMAIN_NAME}"
    ports:
      - 8083
    volumes:
      - ../data/owntracks/config:/owntracks
      - ../data/owntracks/store:/store
    restart: unless-stopped
    environment:
      - OTR_PORT=0 # disable mqtt if 0
      - OTR_HOST=owntracks-mqtt
      - OTR_HTTPPORT=8083
      - PUID=1000
      - PGID=1000
      - OTR_STORAGEDIR=/store
    labels:
      - traefik.enable=true
      - traefik.http.routers.owntracks.rule=Host(`${OWNTRACKS_HOST}.${DOMAIN_NAME}`)
      - traefik.http.routers.owntracks.entrypoints=websecure
      - traefik.http.routers.owntracks.tls.certresolver=mydnschallenge
#      - traefik.http.middlewares.owntrackslist.ipwhitelist.sourcerange=192.168.0.0/24, 10.13.13.0/24, 127.0.0.1/32, 185.123.53.148/32
#      - traefik.http.routers.owntracks.middlewares=owntrackslist
      - traefik.http.services.owntracks.loadbalancer.server.port=8083
