services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    volumes:
      - ../data/perplexica/searxng:/etc/searxng:rw
    expose:
      - 8080
    networks:
      - traefik-network
    restart: unless-stopped

  perplexica:
    image: itzcrazykns1337/perplexica:main
    container_name: perplexica
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
    expose:
      - 3000
    networks:
      - traefik-network
    volumes:
      - ../data/perplexica/data:/home/perplexica/data
      - ../data/perplexica/uploads:/home/perplexica/uploads
      - ../data/perplexica/config.toml:/home/perplexica/config.toml
    restart: unless-stopped

networks:
  default:
    name: traefik-network
    external: true

volumes:
  backend-dbstore:
  uploads:
