version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM="claim-mBWf_FXSdKwkYfzzPFZf"
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
      - "3005:3005"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ../data/plex/config:/config
      - ${CONTENT_DIR}/plex/tv:/tv
      - ${CONTENT_DIR}/plex/movies:/movies
      - ${CONTENT_DIR}/plex/music/:/music
      - ${CONTENT_DIR}/plex/likedMusic/:/likedMusic
    restart: unless-stopped
