version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=9092
    volumes:
      - ../data/qbittorrent/config/:/config
      - ../data/qbittorrent/webgui/:/webgui
      - ${CONTENT_DIR}/torrent/movies:/downloads/movies
      - ${CONTENT_DIR}/torrent/tv/:/downloads/serials
      - ${CONTENT_DIR}/torrent/seedMusic:/downloads/seedMusic
      - ${CONTENT_DIR}/torrent/music/:/downloads/music
    ports:
      - 9092:9092
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
