version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/radarr/config:/config
      - ${CONTENT_DIR}/torrent/movies:/downloads
      - ${CONTENT_DIR}/plex/movies:/movies
    restart: unless-stopped
