version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: "${RADARR_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/radarr/config:/config
      - /home/ksmi/a/torrent/movies:/downloads
      - /home/ksmi/a/plex/movies:/movies
    restart: unless-stopped
