version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/sonarr/config:/config
      - ${CONTENT_DIR}/torrent/tv:/downloads
      - ${CONTENT_DIR}/plex/tv:/tv
    restart: unless-stopped
