version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: "${SONARR_HOST}.${DOMAIN_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../data/sonarr/config:/config
      - /home/ksmi/a/torrent/tv:/downloads
      - /home/ksmi/a/plex/tv:/tv
    restart: unless-stopped
