version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    volumes:
      - ${DATA_DIR}/tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tbilisi
    restart: unless-stopped
