version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  traefik:
    image: traefik:latest
    read_only: true
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/traefik/traefik.yaml:/traefik.yaml:ro
      - ../data/traefik/servicesConfig.yaml:/servicesConfig.yaml:ro
      - ../data/traefik/etc/traefik:/etc/traefik/
      - ../data/traefik/srv/letsencrypt:/letsencrypt
    environment:
      - SITE_HOST=${DOMAIN_NAME}
      - ADGUARD_HOST=${ADGUARD_HOST}.${DOMAIN_NAME}
    restart: unless-stopped
