version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  wireguard:
    container_name: wireguard
    hostname: wireguard
    image: kizzx2/wireguard-socks-proxy
    volumes:
      - ${DATA_DIR}/wireguard:/etc/wireguard/:ro
    ports:
      - 1080:1080
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
