version: "3.7"

services:
  wireguard_server:
    container_name: wireguard_server
    hostname: wireguard_server
    image: linuxserver/wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERPORT=51830
      - PEERS=${VPN_PEERS}
      - PEERDNS=${VPN_PEERDNS}
      - INTERNAL_SUBNET=${VPN_INTERNAL_SUBNET}
      - ALLOWEDIPS=${VPN_ALLOWEDIPS}
      - LOG_CONFS=true
    volumes:
      - ../data/wireguard-server:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
