version: "3.7"

#networks:
#  default:
#    name: traefik-network
#    external: true

#xray docker run -d -p 1080:1080 --name xray --restart=always -v /Users/ksmi/xray:/etc/xray teddysun/xray
services:
  xray_proxy:
    container_name: xray_proxy
    hostname: xray_proxy
    image: teddysun/xray
    volumes:
      - ../data/xray-proxy:/etc/xray
    ports:
      - 10808:10808
      - 9889:8888
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
