version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  youtrack:
    image: jetbrains/youtrack:latest
    container_name: youtrack
    hostname: "${YOUTRACK_HOST}.${PROMFIS_DOMAIN}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../data/youtrack/app/srv/youtrack/data/:/opt/youtrack/data
      - ../data/youtrack/app/srv/youtrack/conf/:/opt/youtrack/conf
      - ../data/youtrack/app/srv/youtrack/logs/:/opt/youtrack/logs
      - ../data/youtrack/app/srv/youtrack/backups/:/opt/youtrack/backups
    restart: unless-stopped