version: "3.7"

networks:
  default:
    name: traefik-network
    external: true

services:
  youtrack:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack"
    hostname: "${YOUTRACK_HOST}.${PROMFIS_DOMAIN}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../data/youtrack/app/srv/youtrack/data/:/opt/youtrack/data
      - ../data/youtrack/app/srv/youtrack/conf/:/opt/youtrack/conf
      - ../data/youtrack/app/srv/youtrack/logs/:/opt/youtrack/logs
      - ../data/youtrack/app/srv/youtrack/backups/:/opt/youtrack/backups
    labels:
      - traefik.enable=true
      - traefik.http.routers.${YOUTRACK_HOST}.rule=Host(`${YOUTRACK_HOST}.${PROMFIS_DOMAIN}`)
      - traefik.http.routers.${YOUTRACK_HOST}.entrypoints=websecure
      - traefik.http.routers.${YOUTRACK_HOST}.tls.certresolver=mydnschallenge
      - traefik.http.services.${YOUTRACK_HOST}.loadbalancer.server.port=8080
      - traefik.http.middlewares.${YOUTRACK_HOST}.headers.STSPreload=true
      - traefik.http.middlewares.${YOUTRACK_HOST}.headers.STSSeconds=315360000
    restart: unless-stopped
